apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nodeprofiles.htas.cloud
spec:
  group: htas.cloud
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                instanceName:
                  type: string
                instanceType:
                  type: string
                cpuCapacity:
                  type: number
                memoryCapacity:
                  type: number
                cpuAvailable:
                  type: number
                memoryAvailable:
                  type: number
                runtime:
                  type: integer
  scope: Namespaced
  names:
    plural: nodeprofiles
    singular: nodeprofile
    kind: NodeProfile
    shortNames:
      - np
