apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-profiler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-profiler
  template:
    metadata:
      labels:
        app: resource-profiler
    spec:
      containers:
      - name: resource-profiler
        image: gcr.io/vcc-kubernetes/resource-profiler:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: resource-profiler
spec:
  selector:
    app: resource-profiler
  ports:
  - port: 8080
    targetPort: 8080


apiVersion: v1
kind: ServiceAccount
metadata:
  name: resource-profiler-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resource-profiler-role
rules:
- apiGroups: [""]
  resources: ["nodes", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["htas.cloud"]
  resources: ["nodeprofiles"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: resource-profiler-binding
subjects:
- kind: ServiceAccount
  name: resource-profiler-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: resource-profiler-role
  apiGroup: rbac.authorization.k8s.io
