apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-packer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-packer
  template:
    metadata:
      labels:
        app: task-packer
    spec:
      serviceAccountName: task-packer-sa
      containers:
      - name: task-packer
        image: gcr.io/vcc-kubernetes/task-packer:v1
        env:
        - name: RESOURCE_PROFILER_URL
          value: "http://resource-profiler:8080"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: task-packer-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: task-packer-role
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["htas.cloud"]
  resources: ["nodeprofiles"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: task-packer-binding
subjects:
- kind: ServiceAccount
  name: task-packer-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: task-packer-role
  apiGroup: rbac.authorization.k8s.io
